import 'package:flutter/material.dart';
import 'package:gerrymanderx/providers/map_data_store.dart';
import 'package:gerrymanderx/providers/map_state_store.dart';
import 'package:gerrymanderx/models/geo_cell.dart';

/// Party IDs as generated by import_to_sqlite.py:
///   1 = Democrat (D), 2 = Republican (R), 3 = Libertarian (L),
///   4 = Green (G), 5 = Independent (I), 6 = Write-In (W), 7 = Other (O)
const _partyColors = <int, Color>{
  1: Color(0xFF2166AC), // Democrat – blue
  2: Color(0xFFB2182B), // Republican – red
  3: Color(0xFFFFC107), // Libertarian – gold
  4: Color(0xFF4CAF50), // Green
  5: Color(0xFF9E9E9E), // Independent – grey
  6: Color(0xFF757575), // Write-In
  7: Color(0xFF616161), // Other
};

const _defaultCellColor = Color(0xFF333333);

class MapPainter extends CustomPainter {
  final MapDataStore dataStore;
  final List<LayerType> visibleLayers;
  final LayerType interactiveLayer;
  final FillMode fillMode;
  final int? selectedCellId;
  final int? hoveredCellId;
  final int? singleCandidateId;

  MapPainter({
    required this.dataStore,
    required this.visibleLayers,
    required this.interactiveLayer,
    required this.fillMode,
    this.selectedCellId,
    this.hoveredCellId,
    this.singleCandidateId,
  });

  @override
  void paint(Canvas canvas, Size size) {
    if (dataStore.isLoadingData.value || dataStore.overallBounds.value == null) {
      return;
    }

    final bounds = dataStore.overallBounds.value!;

    final scaleX = size.width / bounds.width;
    final scaleY = size.height / bounds.height;
    final scale = scaleX < scaleY ? scaleX : scaleY;

    final mapWidth = bounds.width * scale;
    final mapHeight = bounds.height * scale;
    final offsetX = (size.width - mapWidth) / 2 - bounds.left * scale;
    final offsetY = (size.height - mapHeight) / 2 - bounds.top * scale;

    canvas.save();
    canvas.translate(offsetX, offsetY);
    canvas.scale(scale, scale);

    // Draw from bottom to top.
    if (visibleLayers.contains(LayerType.state)) {
      _drawLayer(canvas, dataStore.states.value, LayerType.state, scale);
    }
    if (visibleLayers.contains(LayerType.congressionalDistrict)) {
      _drawLayer(canvas, dataStore.congressionalDistricts.value, LayerType.congressionalDistrict, scale);
    }
    if (visibleLayers.contains(LayerType.county)) {
      _drawLayer(canvas, dataStore.counties.value, LayerType.county, scale);
    }
    if (visibleLayers.contains(LayerType.precinct)) {
      _drawLayer(canvas, dataStore.precincts.value, LayerType.precinct, scale);
    }

    canvas.restore();
  }

  void _drawLayer(Canvas canvas, List<RenderableCell> cells, LayerType layerType, double mapScale) {
    double borderThickness;
    switch (layerType) {
      case LayerType.state:
        borderThickness = 3.0;
      case LayerType.congressionalDistrict:
      case LayerType.county:
        borderThickness = 1.5;
      case LayerType.precinct:
        borderThickness = 0.5;
    }

    final actualThickness = borderThickness / mapScale;

    final borderPaint = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = actualThickness;

    // Border color: white for state/district, subtle for precincts.
    borderPaint.color = layerType == LayerType.precinct
        ? Colors.white24
        : Colors.white54;

    final votes = dataStore.precinctVotes.value;
    final partyMap = dataStore.candidatePartyMap.value;

    for (final rCell in cells) {
      final isHovered = (layerType == interactiveLayer && rCell.cell.id == hoveredCellId);
      final isSelected = (layerType == interactiveLayer && rCell.cell.id == selectedCellId);

      // --- Compute fill color based on FillMode ---
      Color fillColor;

      if (layerType == LayerType.precinct) {
        fillColor = _precinctFillColor(rCell.cell.id, votes, partyMap);
      } else {
        // Non-precinct layers: translucent so precincts show through.
        fillColor = Colors.transparent;
      }

      // Override for interaction.
      if (isSelected) {
        fillColor = Colors.white.withOpacity(0.6);
      } else if (isHovered) {
        fillColor = Color.lerp(fillColor, Colors.white, 0.35)!;
      }

      if (fillColor != Colors.transparent) {
        canvas.drawPath(rCell.path, Paint()
          ..color = fillColor
          ..style = PaintingStyle.fill);
      }
      canvas.drawPath(rCell.path, borderPaint);
    }
  }

  Color _precinctFillColor(
    int precinctId,
    Map<int, PrecinctVoteSummary> votes,
    Map<int, int> partyMap,
  ) {
    final summary = votes[precinctId];
    if (summary == null || summary.totalVotes == 0) {
      return _defaultCellColor;
    }

    switch (fillMode) {
      case FillMode.winnerOpaque:
        final partyId = partyMap[summary.winnerCandidateId] ?? 0;
        return _partyColors[partyId] ?? _defaultCellColor;

      case FillMode.winnerOpacity:
        final partyId = partyMap[summary.winnerCandidateId] ?? 0;
        final baseColor = _partyColors[partyId] ?? _defaultCellColor;
        // Margin: winner share of total. Strong win → full opacity.
        final margin = summary.winnerVotes / summary.totalVotes;
        return baseColor.withOpacity((margin * 1.5).clamp(0.3, 1.0));

      case FillMode.singleCandidateOpacity:
        if (singleCandidateId == null) return _defaultCellColor;
        final candidateVotes = summary.candidateVotes[singleCandidateId] ?? 0;
        final share = candidateVotes / summary.totalVotes;
        final partyId = partyMap[singleCandidateId] ?? 0;
        final baseColor = _partyColors[partyId] ?? _defaultCellColor;
        return baseColor.withOpacity(share.clamp(0.05, 1.0));

      case FillMode.turnoutGray:
        // Turnout = totalVotes / population.
        final pop = summary.totalVotes * 1.8; // same mock formula
        final turnout = summary.totalVotes / pop;
        final gray = (turnout * 255).round().clamp(30, 240);
        return Color.fromARGB(255, gray, gray, gray);

      case FillMode.dotDensity:
        // Dot density is complex; for now use a subtle base with winner tint.
        final partyId = partyMap[summary.winnerCandidateId] ?? 0;
        return (_partyColors[partyId] ?? _defaultCellColor).withOpacity(0.25);
    }
  }

  @override
  bool shouldRepaint(covariant MapPainter oldDelegate) {
    return oldDelegate.visibleLayers != visibleLayers ||
        oldDelegate.interactiveLayer != interactiveLayer ||
        oldDelegate.fillMode != fillMode ||
        oldDelegate.selectedCellId != selectedCellId ||
        oldDelegate.hoveredCellId != hoveredCellId ||
        oldDelegate.singleCandidateId != singleCandidateId ||
        oldDelegate.dataStore.isLoadingData.value != dataStore.isLoadingData.value;
  }
}
